// GENERATED by scripts/build-brand-library.mjs. Do not edit by hand.
// Source: the master brand library outside this repo. Re-run the script when
// Communications updates it.
//
// Paths are relative to shared/assets/brand/library/.

export const BRAND_LIBRARY = [
  {
    "id": "wordmark",
    "title": "Cornerstone logo",
    "blurb": "The full wordmark. Use this first unless space forces the icon.",
    "src": "Logos/Cornerstone Full Logo",
    "assets": [
      {
        "name": "Horizontal",
        "variant": "black",
        "png": "wordmark/wordmark-horizontal-black.png",
        "jpg": "wordmark/wordmark-horizontal-black.jpg"
      },
      {
        "name": "Horizontal",
        "variant": "blue",
        "png": "wordmark/wordmark-horizontal-blue.png",
        "jpg": "wordmark/wordmark-horizontal-blue.jpg"
      },
      {
        "name": "Horizontal",
        "variant": "white",
        "png": "wordmark/wordmark-horizontal-white.png",
        "jpg": "wordmark/wordmark-horizontal-white.jpg"
      },
      {
        "name": "Stacked",
        "variant": "black",
        "png": "wordmark/wordmark-stacked-black.png",
        "jpg": "wordmark/wordmark-stacked-black.jpg"
      },
      {
        "name": "Stacked",
        "variant": "blue",
        "png": "wordmark/wordmark-stacked-blue.png",
        "jpg": "wordmark/wordmark-stacked-blue.jpg"
      },
      {
        "name": "Stacked",
        "variant": "white",
        "png": "wordmark/wordmark-stacked-white.png",
        "jpg": "wordmark/wordmark-stacked-white.jpg"
      }
    ]
  },
  {
    "id": "icon",
    "title": "Cornerstone icon",
    "blurb": "The mark on its own. For avatars, favicons and tight spaces.",
    "src": "Icons/Cornerstone",
    "assets": [
      {
        "name": "Outline",
        "variant": "black",
        "png": "icon/icon-outline-black.png",
        "jpg": "icon/icon-outline-black.jpg"
      },
      {
        "name": "Outline",
        "variant": "blue",
        "png": "icon/icon-outline-blue.png",
        "jpg": "icon/icon-outline-blue.jpg"
      },
      {
        "name": "Outline",
        "variant": "white",
        "png": "icon/icon-outline-white.png",
        "jpg": "icon/icon-outline-white.jpg"
      },
      {
        "name": "Solid",
        "variant": "black",
        "png": "icon/icon-solid-black.png",
        "jpg": "icon/icon-solid-black.jpg"
      },
      {
        "name": "Solid",
        "variant": "blue",
        "png": "icon/icon-solid-blue.png",
        "jpg": "icon/icon-solid-blue.jpg"
      },
      {
        "name": "Solid",
        "variant": "white",
        "png": "icon/icon-solid-white.png",
        "jpg": "icon/icon-solid-white.jpg"
      }
    ]
  },
  {
    "id": "campus",
    "title": "Campus logos",
    "blurb": "One per campus. Use the campus mark for campus-specific material.",
    "src": "Logos/Campus Logos",
    "assets": [
      {
        "name": "Brentwood",
        "variant": "black",
        "png": "campus/campus-brentwood-black.png",
        "jpg": "campus/campus-brentwood-black.jpg"
      },
      {
        "name": "Brentwood",
        "variant": "white",
        "png": "campus/campus-brentwood-white.png",
        "jpg": "campus/campus-brentwood-white.jpg"
      },
      {
        "name": "Livermore",
        "variant": "black",
        "png": "campus/campus-livermore-black.png",
        "jpg": "campus/campus-livermore-black.jpg"
      },
      {
        "name": "Livermore",
        "variant": "white",
        "png": "campus/campus-livermore-white.png",
        "jpg": "campus/campus-livermore-white.jpg"
      },
      {
        "name": "Walnut Creek",
        "variant": "black",
        "png": "campus/campus-walnut-creek-black.png",
        "jpg": "campus/campus-walnut-creek-black.jpg"
      },
      {
        "name": "Walnut Creek",
        "variant": "white",
        "png": "campus/campus-walnut-creek-white.png",
        "jpg": "campus/campus-walnut-creek-white.jpg"
      }
    ]
  },
  {
    "id": "campus-icon",
    "title": "Campus icons",
    "blurb": "The icon form of each campus mark.",
    "src": "Icons/Campus",
    "assets": [
      {
        "name": "Brentwood",
        "variant": "default",
        "png": "campus-icon/campus-icon-brentwood-default.png",
        "jpg": "campus-icon/campus-icon-brentwood-default.jpg"
      },
      {
        "name": "Brentwood",
        "variant": "white",
        "png": "campus-icon/campus-icon-brentwood-white.png",
        "jpg": "campus-icon/campus-icon-brentwood-white.jpg"
      },
      {
        "name": "Livermore",
        "variant": "black",
        "png": "campus-icon/campus-icon-livermore-black.png",
        "jpg": "campus-icon/campus-icon-livermore-black.jpg"
      },
      {
        "name": "Livermore",
        "variant": "white",
        "png": "campus-icon/campus-icon-livermore-white.png",
        "jpg": "campus-icon/campus-icon-livermore-white.jpg"
      },
      {
        "name": "Walnut Creek",
        "variant": "black",
        "png": "campus-icon/campus-icon-walnut-creek-black.png",
        "jpg": "campus-icon/campus-icon-walnut-creek-black.jpg"
      },
      {
        "name": "Walnut Creek",
        "variant": "white",
        "png": "campus-icon/campus-icon-walnut-creek-white.png",
        "jpg": "campus-icon/campus-icon-walnut-creek-white.jpg"
      }
    ]
  },
  {
    "id": "ministry",
    "title": "Ministry logos",
    "blurb": "One per ministry team.",
    "src": "Logos/Ministry Logos",
    "assets": [
      {
        "name": "Care",
        "variant": "black",
        "png": "ministry/ministry-care-black.png",
        "jpg": "ministry/ministry-care-black.jpg"
      },
      {
        "name": "Care",
        "variant": "white",
        "png": "ministry/ministry-care-white.png",
        "jpg": "ministry/ministry-care-white.jpg"
      },
      {
        "name": "Community",
        "variant": "black",
        "png": "ministry/ministry-community-black.png",
        "jpg": "ministry/ministry-community-black.jpg"
      },
      {
        "name": "Community",
        "variant": "white",
        "png": "ministry/ministry-community-white.png",
        "jpg": "ministry/ministry-community-white.jpg"
      },
      {
        "name": "Facilities",
        "variant": "black",
        "png": "ministry/ministry-facilities-black.png",
        "jpg": "ministry/ministry-facilities-black.jpg"
      },
      {
        "name": "Facilities",
        "variant": "white",
        "png": "ministry/ministry-facilities-white.png",
        "jpg": "ministry/ministry-facilities-white.jpg"
      },
      {
        "name": "Guest Services",
        "variant": "black",
        "png": "ministry/ministry-guest-services-black.png",
        "jpg": "ministry/ministry-guest-services-black.jpg"
      },
      {
        "name": "Guest Services",
        "variant": "white",
        "png": "ministry/ministry-guest-services-white.png",
        "jpg": "ministry/ministry-guest-services-white.jpg"
      },
      {
        "name": "Kids",
        "variant": "black",
        "png": "ministry/ministry-kids-black.png",
        "jpg": "ministry/ministry-kids-black.jpg"
      },
      {
        "name": "Kids",
        "variant": "white",
        "png": "ministry/ministry-kids-white.png",
        "jpg": "ministry/ministry-kids-white.jpg"
      },
      {
        "name": "Next Steps",
        "variant": "black",
        "png": "ministry/ministry-next-steps-black.png",
        "jpg": "ministry/ministry-next-steps-black.jpg"
      },
      {
        "name": "Next Steps",
        "variant": "white",
        "png": "ministry/ministry-next-steps-white.png",
        "jpg": "ministry/ministry-next-steps-white.jpg"
      },
      {
        "name": "Outreach",
        "variant": "black",
        "png": "ministry/ministry-outreach-black.png",
        "jpg": "ministry/ministry-outreach-black.jpg"
      },
      {
        "name": "Outreach",
        "variant": "white",
        "png": "ministry/ministry-outreach-white.png",
        "jpg": "ministry/ministry-outreach-white.jpg"
      },
      {
        "name": "Production",
        "variant": "black",
        "png": "ministry/ministry-production-black.png",
        "jpg": "ministry/ministry-production-black.jpg"
      },
      {
        "name": "Production",
        "variant": "white",
        "png": "ministry/ministry-production-white.png",
        "jpg": "ministry/ministry-production-white.jpg"
      },
      {
        "name": "Students",
        "variant": "black",
        "png": "ministry/ministry-students-black.png",
        "jpg": "ministry/ministry-students-black.jpg"
      },
      {
        "name": "Students",
        "variant": "white",
        "png": "ministry/ministry-students-white.png",
        "jpg": "ministry/ministry-students-white.jpg"
      },
      {
        "name": "Women",
        "variant": "black",
        "png": "ministry/ministry-women-black.png",
        "jpg": "ministry/ministry-women-black.jpg"
      },
      {
        "name": "Women",
        "variant": "white",
        "png": "ministry/ministry-women-white.png",
        "jpg": "ministry/ministry-women-white.jpg"
      },
      {
        "name": "Worship",
        "variant": "black",
        "png": "ministry/ministry-worship-black.png",
        "jpg": "ministry/ministry-worship-black.jpg"
      },
      {
        "name": "Worship",
        "variant": "white",
        "png": "ministry/ministry-worship-white.png",
        "jpg": "ministry/ministry-worship-white.jpg"
      }
    ]
  }
];
